# Example configuration for different environments

# Development environment (config.yaml)
server:
  name: "mcp-defect-dojo-dev"
  version: "v0.1.0"
  instructions: "MCP server for DefectDojo integration - Development Environment"
  host: "localhost"
  port: 8000
  transport: "stdio"

defectdojo:
  base_url: "http://localhost:8080"
  api_key: ""  # Set via parameter or environment variable for security
  api_version: "v2"
  request_timeout: "30s"

logging:
  level: "debug"  # More verbose logging for development
  format: "text"

---
# Production environment (config.prod.yaml)
server:
  name: "mcp-defect-dojo-prod"
  version: "v0.1.0"
  instructions: "MCP server for DefectDojo integration - Production Environment"
  host: "0.0.0.0"
  port: 443
  transport: "http"

defectdojo:
  base_url: "https://defectdojo.company.com"
  api_key: ""  # Always set via environment variable in production
  api_version: "v2"
  request_timeout: "60s"  # Longer timeout for production

logging:
  level: "info"
  format: "json"  # Structured logging for production
